# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: phperrot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/20 13:27:18 by phperrot          #+#    #+#              #
#    Updated: 2018/07/24 17:34:12 by phperrot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: compilation

compilation:
	gcc ft_cat.c -o ft_cat

clean:
	rm ft_cat

fclean: clean
	rm ft_cat
