#define KICK "kick"
#define PUNCH "punch"
#define HEADBUTT "headbutt"
#define KICK1 "chop ichi"
#define KICK2 "chop ni"
#define KICK3 "chop san"
#define KICK4 "chop shi"
#define KICK5 "chop go"
#define KICK6 "chop roku"
#define KICK7 "chop shichi"
#define KICK8 "chop hachi"
#define KICK9 "chop ku"
#define	KICK10 "chop ju"
#define KICK11 "chop hyaku"
#define KICK12 "chop sen"
#include "ft_ultimate_fight.c"
