# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: phperrot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/20 13:27:18 by phperrot          #+#    #+#              #
#    Updated: 2018/07/25 20:59:04 by phperrot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: compilation

compilation:
	gcc -Werror -Wall -Wextra ft_tail.c ft_side_functions.c\
	   	ft_display_functions.c -I ft_header.h -o ft_tail

clean:

fclean: clean
	rm ft_tail
