# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: phperrot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/20 13:27:18 by phperrot          #+#    #+#              #
#    Updated: 2018/07/25 09:43:57 by phperrot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: compilation

compilation:
	gcc -Werror -Wall -Wextra ft_hexdump.c ft_base_converter.c -I ft_header.h -o ft_hexdump

clean:

fclean: clean
	rm ft_hexdump
